# End To End Test

# IMPORTANT: depends on the main docker-compose.yml

# USAGE
# It will run the tests, print a report and exit
#   cd pagy-on-docker
#   docker-compose -f docker-compose.yml \
#                  -f docker-compose.e2e-test.yml \
#                   up ruby e2e-test

version: "3.8"
services:
  # depends on the main ruby docker-compose setup
  # this changes the command to run the test app that cypress needs
  ruby:
    command: rackup --quiet -o 0.0.0.0 -p 4567 test/e2e/pagy_app.ru

  e2e-test:
    depends_on:
      - ruby
    image: pagy-e2e-test:latest
    build:
      context: .
      dockerfile: Dockerfile.e2e-test
    container_name: pagy-e2e-test
    environment:
      - CYPRESS_baseUrl=http://ruby:4567
    working_dir: /pagy/test/e2e
    volumes:
      - ..:/pagy # repo dir mount
