# Ruby dev and test environment
# it will keep the installed gems and HOME in the pagy_bundle and pagy_user_home volumes

# USAGE
#   cd pagy-on-docker
#   docker-compose up ruby           # ruby dev and test environment service

version: "3.8"
services:
  # ruby dev and test pagy development
  ruby:
    image: pagy-ruby-${RUBY_VARIANT:-3}:latest
    build:
      context: .
      dockerfile: Dockerfile.ruby-${RUBY_VARIANT:-3}
      args:
        user: $USER
        group: $GROUP
        uid: $UID
        gid: $GID
        password: $PASSWORD
        term: $TERM
    container_name: pagy-ruby
    volumes:
      - ..:/pagy # repo dir mount
      - ruby_bundle:/usr/local/bundle
      - ruby_user_home:/home/$USER
    environment:
      - HTML_REPORTS    # HTML reports of test coverage from local ENV
    stdin_open: true
    tty: true

volumes:
  ruby_bundle:
    name: pagy_ruby_bundle
  ruby_user_home:
    name: pagy_ruby_user_home
